export const FAKE_SSH_ENV_NAMES = [
  "FAKE_SSH_CHECK_MISS_MARKER",
  "FAKE_SSH_CHECK_MISS_RELEASE",
  "FAKE_SSH_CHUNKS",
  "FAKE_SSH_COMMAND_DELAY_MS",
  "FAKE_SSH_CONTROL_EXIT_CODE",
  "FAKE_SSH_EXIT_CODE",
  "FAKE_SSH_FAIL_UNMATCHED",
  "FAKE_SSH_INPUT",
  "FAKE_SSH_INPUT_LOG",
  "FAKE_SSH_LOG",
  "FAKE_SSH_MASTER_EXIT_CODE",
  "FAKE_SSH_MASTER_EXIT_DELAY_MS",
  "FAKE_SSH_MASTER_EXIT_MARKER",
  "FAKE_SSH_NEVER_READY",
  "FAKE_SSH_PID_LOG",
  "FAKE_SSH_READY_DELAY_MS",
  "FAKE_SSH_REQUIRE_LIVE_MASTER",
  "FAKE_SSH_RESPONSES",
  "FAKE_SSH_STDERR",
  "FAKE_SSH_STDOUT",
] as const

export const FAKE_SFTP_ENV_NAMES = [
  "FAKE_SFTP_DELAY_MS",
  "FAKE_SFTP_EXIT_CODE",
  "FAKE_SFTP_EXPECT_INPUT",
  "FAKE_SFTP_INPUT",
  "FAKE_SFTP_INPUT_LOG",
  "FAKE_SFTP_LOG",
  "FAKE_SFTP_STDERR",
  "FAKE_SFTP_STDOUT",
] as const

export const FAKE_OPENCODE_ENV_NAMES = [
  "FAKE_OPENCODE_ACTIVE_MARKER",
  "FAKE_OPENCODE_ACTIVE_MARKER_DELAY_MS",
  "FAKE_OPENCODE_DELAY_MS",
  "FAKE_OPENCODE_DESCENDANT_PID_FILE",
  "FAKE_OPENCODE_EXIT_CODE",
  "FAKE_OPENCODE_IGNORE_SIGTERM",
  "FAKE_OPENCODE_LOG",
  "FAKE_OPENCODE_PID_FILE",
  "FAKE_OPENCODE_READY_MARKER",
  "FAKE_OPENCODE_REAL_BIN",
  "FAKE_OPENCODE_REPLACE_CHILD_PROVENANCE",
  "FAKE_OPENCODE_SERVE",
  "FAKE_OPENCODE_SERVE_AUTO_EXIT_AFTER_READY",
  "FAKE_OPENCODE_SERVE_AUTO_EXIT_STATE",
  "FAKE_OPENCODE_SERVE_STATE",
  "FAKE_OPENCODE_SPAWN_DESCENDANT",
  "FAKE_OPENCODE_START_MARKER",
  "FAKE_OPENCODE_VERSION_DELAY_MS",
  "FAKE_OPENCODE_VERSION_EXIT_CODE",
  "FAKE_OPENCODE_VERSION_STDERR",
  "FAKE_OPENCODE_VERSION_STDOUT",
  "FAKE_OPENCODE_WRITE_READY",
] as const

export const FIXTURE_CONTROL_ENV_NAMES = [
  ...FAKE_SSH_ENV_NAMES,
  ...FAKE_SFTP_ENV_NAMES,
  ...FAKE_OPENCODE_ENV_NAMES,
  "OPENCODE_PURE",
  "OPENCODE_SSH_OPENCODE_BIN",
  "npm_config_opencode_ssh_expected_https_proxy",
] as const

export function scrubFixtureEnvironment(
  source: NodeJS.ProcessEnv
): NodeJS.ProcessEnv {
  const result = { ...source }
  for (const name of FIXTURE_CONTROL_ENV_NAMES) delete result[name]
  return result
}
